version: "3.8"
services:
  db:
    container_name: DATABASE
    image: postgres:13
    restart: always    
    volumes:    
      - db_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password

  rails:
    container_name: BACKEND
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - db
volumes: 
  db_data: